version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: awsan_n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
    volumes:
      - ./n8n_data:/home/node/.n8n

  livekit:
    image: livekit/livekit-server:v1.8
    container_name: awsan_livekit
    command: --dev
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
